language: scala
sudo: false
dist: xenial
scala:
  - 2.12.8
jdk:
  - openjdk8
before_install:
  - export PATH=${PATH}:./vendor/bundle
script:
  - sbt tut
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck scalafmtSbtCheck test:run
